'use client'

import { useEffect, useState } from 'react'
import { useRouter } from 'next/navigation'
import { ArrowLeft, Crown, UserPlus, Users, Trophy } from 'lucide-react'
import { supabase } from '@/lib/supabase'

type Team={id:string;name:string;created_by:string|null}; type Member={player_id:string;role:string;full_name:string|null;avatar_url:string|null}; type Request={id:string;player_id:string;full_name:string|null}
export default function TeamPage(){const router=useRouter();const [teams,setTeams]=useState<Team[]>([]);const [team,setTeam]=useState<Team|null>(null);const [members,setMembers]=useState<Member[]>([]);const [requests,setRequests]=useState<Request[]>([]);const [name,setName]=useState('');const [busy,setBusy]=useState(false);const [msg,setMsg]=useState('')
 async function load(){const {data:{user}}=await supabase.auth.getUser();if(!user){router.replace('/login');return};const {data:ms}=await supabase.from('team_members').select('team_id').eq('player_id',user.id);const ids=(ms||[]).map(x=>x.team_id);const {data:ts}=ids.length?await supabase.from('teams').select('id,name,created_by').in('id',ids):{data:[] as Team[]};setTeams(ts||[]);const selected=team&&ts?.find(t=>t.id===team.id)||ts?.[0]||null;setTeam(selected);if(selected){const {data:mem}=await supabase.from('team_members').select('player_id,role').eq('team_id',selected.id);const pids=(mem||[]).map(x=>x.player_id);const {data:ps}=pids.length?await supabase.from('profiles').select('id,full_name,avatar_url').in('id',pids):{data:[] as any[]};setMembers((mem||[]).map(m=>{const p=(ps||[]).find((x:any)=>x.id===m.player_id);return {...m,full_name:p?.full_name||'Player',avatar_url:p?.avatar_url||null}}));const {data:req}=await supabase.from('team_join_requests').select('id,player_id,status').eq('team_id',selected.id).eq('status','pending');const rids=(req||[]).map(x=>x.player_id);const {data:rps}=rids.length?await supabase.from('profiles').select('id,full_name').in('id',rids):{data:[] as any[]};setRequests((req||[]).map(r=>({id:r.id,player_id:r.player_id,full_name:(rps||[]).find((p:any)=>p.id===r.player_id)?.full_name||'Player'})))} }
 useEffect(()=>{load()},[])
 async function createTeam(){if(!name.trim())return;setBusy(true);const {data:{user}}=await supabase.auth.getUser();const {data:t,error}=await supabase.from('teams').insert({name:name.trim(),created_by:user?.id}).select('id,name,created_by').single();if(error)setMsg(error.message);else{await supabase.from('team_members').insert({team_id:t.id,player_id:user?.id,role:'manager'});setName('');setMsg('Team created successfully.');await load()}setBusy(false)}
 async function decide(reqId:string,accept:boolean){setBusy(true);const {error}=await supabase.rpc(accept?'accept_team_join_request':'reject_team_join_request',{p_request_id:reqId});setMsg(error?.message|| (accept?'Player accepted.':'Request rejected.'));await load();setBusy(false)}
 const manager=!!team?.created_by;return <main className="form-shell"><header className="topbar"><div className="brand"><Trophy size={22}/><span>Bosslive</span></div><button className="secondary-btn" onClick={()=>router.push('/dashboard')}><ArrowLeft size={16}/> Dashboard</button></header><section className="form-page"><span className="eyebrow"><Users size={13}/> MY TEAM</span><h1>Team management</h1>{teams.length>1&&<select value={team?.id||''} onChange={e=>setTeam(teams.find(t=>t.id===e.target.value)||null)}><option value="">Select team</option>{teams.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select>}{team?<><article className="dash-card" style={{marginTop:18}}><span className="card-kicker">TEAM</span><h2>{team.name}</h2><p>{members.length} members · {manager?'Manager access':'Player access'}</p></article><article className="dash-card" style={{marginTop:18}}><span className="card-kicker">MEMBERS</span>{members.map(m=><div key={m.player_id} style={{display:'flex',alignItems:'center',gap:12,padding:'12px 0',borderBottom:'1px solid #edf1ee'}}><div style={{width:42,height:42,borderRadius:'50%',background:'#e8f7ef',display:'grid',placeItems:'center',overflow:'hidden'}}>{m.avatar_url?<img src={m.avatar_url} alt="" style={{width:'100%',height:'100%',objectFit:'cover'}}/>:<Users size={18}/>}</div><div style={{flex:1}}><strong>{m.full_name}</strong><small style={{display:'block',color:'#718078'}}>{m.role}</small></div>{m.role==='manager'&&<Crown size={17} color="#d89b00"/>}</div>)}</article>{manager&&<article className="dash-card" style={{marginTop:18}}><span className="card-kicker"><UserPlus size={13}/> JOIN REQUESTS</span>{requests.length?requests.map(r=><div key={r.id} style={{display:'flex',alignItems:'center',gap:12,padding:'12px 0',borderBottom:'1px solid #edf1ee'}}><strong style={{flex:1}}>{r.full_name}</strong><button className="primary-btn compact" disabled={busy} onClick={()=>decide(r.id,true)}>Accept</button><button className="secondary-btn" disabled={busy} onClick={()=>decide(r.id,false)}>Reject</button></div>):<p>No pending requests.</p>}</article>}</>:<article className="dash-card" style={{marginTop:18}}><h2>No team yet</h2><p>Create your team and become its manager.</p><div style={{display:'flex',gap:10,marginTop:15}}><input value={name} onChange={e=>setName(e.target.value)} placeholder="Team name"/><button className="primary-btn" disabled={busy} onClick={createTeam}>Create Team</button></div></article>}{msg&&<div className="form-success" style={{marginTop:14}}>{msg}</div>}</section></main>}
