'use client'

import { useEffect, useMemo, useState } from 'react'
import { useParams, useRouter } from 'next/navigation'
import { ArrowLeft, Trophy } from 'lucide-react'
import { supabase } from '@/lib/supabase'

type Inn={id:string;batting_team_id:string;bowling_team_id:string;innings_number:number;total_runs:number;wickets:number;total_balls:number;extras:number};type Team={id:string;name:string};type Delivery={striker_id:string;bowler_id:string;runs_batter:number;runs_extras:number;is_wicket:boolean;is_legal_ball:boolean;dismissed_player_id:string|null};type Player={id:string;full_name:string|null}
export default function ScorecardPage(){const {id}=useParams<{id:string}>();const router=useRouter();const [innings,setInnings]=useState<Inn[]>([]);const [teams,setTeams]=useState<Team[]>([]);const [players,setPlayers]=useState<Player[]>([]);const [deliveries,setDeliveries]=useState<Record<string,Delivery[]>>({});const [loading,setLoading]=useState(true)
 useEffect(()=>{(async()=>{const {data:{user}}=await supabase.auth.getUser();if(!user){router.replace('/login');return};const {data:ins}=await supabase.from('innings').select('id,batting_team_id,bowling_team_id,innings_number,total_runs,wickets,total_balls,extras').eq('match_id',id).order('innings_number');setInnings(ins||[]);const tids=[...new Set((ins||[]).flatMap(x=>[x.batting_team_id,x.bowling_team_id]))];const {data:ts}=await supabase.from('teams').select('id,name').in('id',tids);setTeams(ts||[]);const iids=(ins||[]).map(x=>x.id);if(iids.length){const {data:ds}=await supabase.from('deliveries').select('innings_id,striker_id,bowler_id,runs_batter,runs_extras,is_wicket,is_legal_ball,dismissed_player_id').in('innings_id',iids);const g:Record<string,Delivery[]>={};(ds||[]).forEach((d:any)=>(g[d.innings_id]??=[]).push(d));setDeliveries(g);const pids=[...new Set((ds||[]).flatMap((x:any)=>[x.striker_id,x.bowler_id,x.dismissed_player_id].filter(Boolean)))];if(pids.length){const {data:ps}=await supabase.from('profiles').select('id,full_name').in('id',pids as string[]);setPlayers(ps||[])}}setLoading(false)})()},[id,router])
 const tn=(x:string)=>teams.find(t=>t.id===x)?.name||'Team';const pn=(x:string)=>players.find(p=>p.id===x)?.full_name||'Player';
 const stats=(arr:Delivery[])=>{const bat=new Map<string,{runs:number;balls:number;fours:number;sixes:number;out:boolean}>(),bowl=new Map<string,{balls:number;runs:number;wickets:number}>();arr.forEach(d=>{const b=bat.get(d.striker_id)||{runs:0,balls:0,fours:0,sixes:0,out:false};b.runs+=d.runs_batter;b.balls+=d.is_legal_ball?1:0;if(d.runs_batter===4)b.fours++;if(d.runs_batter===6)b.sixes++;if(d.is_wicket&&d.dismissed_player_id===d.striker_id)b.out=true;bat.set(d.striker_id,b);const w=bowl.get(d.bowler_id)||{balls:0,runs:0,wickets:0};w.balls+=d.is_legal_ball?1:0;w.runs+=d.runs_batter+d.runs_extras;if(d.is_wicket&&d.dismissed_player_id)w.wickets++;bowl.set(d.bowler_id,w)});return{bat:[...bat.entries()],bowl:[...bowl.entries()]}}
 if(loading)return <div className="loading-screen">Loading scorecard…</div>;return <main className="form-shell"><header className="topbar"><div className="brand"><Trophy size={22}/><span>Bosslive</span></div><button className="secondary-btn" onClick={()=>router.push(`/matches/${id}/live`)}><ArrowLeft size={16}/> Live match</button></header><section className="form-page"><span className="eyebrow">COMPLETE SCORECARD</span><h1>Match Scorecard</h1>{innings.map(i=>{const s=stats(deliveries[i.id]||[]);return <article className="dash-card" style={{marginTop:18}} key={i.id}><span className="card-kicker">INNINGS {i.innings_number}</span><h2>{tn(i.batting_team_id)} — {i.total_runs}/{i.wickets}</h2><p>{Math.floor(i.total_balls/6)}.{i.total_balls%6} overs · Extras {i.extras||0}</p><h3 style={{marginTop:18}}>Batting</h3>{s.bat.map(([pid,v])=><div key={pid} style={{display:'grid',gridTemplateColumns:'1fr repeat(5,55px)',padding:'10px 0',borderBottom:'1px solid #edf1ee'}}><span>{pn(pid)} {v.out?'• OUT':''}</span><strong>{v.runs}</strong><span>{v.balls}</span><span>{v.fours}</span><span>{v.sixes}</span><span>{v.balls?((v.runs/v.balls)*100).toFixed(1):'0.0'}</span></div>)}<h3 style={{marginTop:18}}>Bowling</h3>{s.bowl.map(([pid,v])=><div key={pid} style={{display:'grid',gridTemplateColumns:'1fr repeat(4,65px)',padding:'10px 0',borderBottom:'1px solid #edf1ee'}}><span>{pn(pid)}</span><strong>{Math.floor(v.balls/6)}.{v.balls%6}</strong><span>{v.runs}</span><span>{v.wickets}</span><span>{v.balls?(v.runs/(v.balls/6)).toFixed(2):'0.00'}</span></div>)}</article>})}</section></main>}
