'use client'

import { useEffect, useMemo, useState } from 'react'
import { useParams, useRouter } from 'next/navigation'
import { ArrowLeft, Trophy } from 'lucide-react'
import { supabase } from '@/lib/supabase'

type Inn = { id:string; batting_team_id:string; bowling_team_id:string; innings_number:number; total_runs:number; wickets:number; total_balls:number }
type Team = {id:string;name:string}
type Delivery = { striker_id:string; bowler_id:string; runs_batter:number; runs_extras:number; is_wicket:boolean; is_legal_ball:boolean; dismissed_player_id:string|null }
type Player = {id:string;full_name:string}

export default function ScorecardPage(){
 const {id}=useParams<{id:string}>(); const router=useRouter(); const [innings,setInnings]=useState<Inn[]>([]); const [teams,setTeams]=useState<Team[]>([]); const [players,setPlayers]=useState<Player[]>([]); const [deliveries,setDeliveries]=useState<Delivery[]>([]); const [loading,setLoading]=useState(true)
 useEffect(()=>{(async()=>{const {data:{user}}=await supabase.auth.getUser();if(!user){router.replace('/login');return}; const {data:ins}=await supabase.from('innings').select('id,batting_team_id,bowling_team_id,innings_number,total_runs,wickets,total_balls').eq('match_id',id).order('innings_number');setInnings(ins||[]); const tids=[...new Set((ins||[]).flatMap(x=>[x.batting_team_id,x.bowling_team_id]))];const {data:ts}=await supabase.from('teams').select('id,name').in('id',tids);setTeams(ts||[]);const {data:ds}=await supabase.from('deliveries').select('striker_id,bowler_id,runs_batter,runs_extras,is_wicket,is_legal_ball,dismissed_player_id').in('innings_id',(ins||[]).map(x=>x.id));setDeliveries(ds||[]);const pids=[...new Set((ds||[]).flatMap(x=>[x.striker_id,x.bowler_id,x.dismissed_player_id].filter(Boolean)))];const {data:ps}=await supabase.from('profiles').select('id,full_name').in('id',pids as string[]);setPlayers(ps||[]);setLoading(false)})()},[id,router])
 const teamName=(x:string)=>teams.find(t=>t.id===x)?.name||'Team';const playerName=(x:string)=>players.find(p=>p.id===x)?.full_name||'Player'
 const batting=useMemo(()=>{const m=new Map<string,{runs:number;balls:number;fours:number;sixes:number;out:boolean}>();deliveries.forEach(d=>{const x=m.get(d.striker_id)||{runs:0,balls:0,fours:0,sixes:0,out:false};x.runs+=d.runs_batter;x.balls+=d.is_legal_ball?1:0;if(d.runs_batter===4)x.fours++;if(d.runs_batter===6)x.sixes++;if(d.is_wicket&&d.dismissed_player_id===d.striker_id)x.out=true;m.set(d.striker_id,x)});return [...m.entries()]},[deliveries])
 const bowling=useMemo(()=>{const m=new Map<string,{balls:number;runs:number;wickets:number}>();deliveries.forEach(d=>{const x=m.get(d.bowler_id)||{balls:0,runs:0,wickets:0};x.balls+=d.is_legal_ball?1:0;x.runs+=d.runs_batter+d.runs_extras;if(d.is_wicket&&d.dismissed_player_id)x.wickets++;m.set(d.bowler_id,x)});return [...m.entries()]},[deliveries])
 if(loading)return <div className="loading-screen">Loading scorecard…</div>
 return <main className="form-shell"><header className="topbar"><div className="brand"><Trophy size={22}/><span>Bosslive</span></div><button className="secondary-btn" onClick={()=>router.push(`/matches/${id}/live`)}><ArrowLeft size={16}/> Live match</button></header><section className="form-page"><span className="eyebrow">SCORECARD</span><h1>Match Scorecard</h1>{innings.map(i=><article className="dash-card" style={{marginTop:18}} key={i.id}><span className="card-kicker">INNINGS {i.innings_number}</span><h2>{teamName(i.batting_team_id)} <strong>{i.total_runs}/{i.wickets}</strong></h2><p>{Math.floor(i.total_balls/6)}.{i.total_balls%6} overs · {teamName(i.bowling_team_id)} bowling</p></article>)}<article className="dash-card" style={{marginTop:18}}><span className="card-kicker">BATTING</span>{batting.map(([pid,s])=><div key={pid} style={{display:'grid',gridTemplateColumns:'1fr repeat(4,70px)',padding:'11px 0',borderBottom:'1px solid #edf1ee'}}><span>{playerName(pid)} {s.out?'• OUT':''}</span><strong>{s.runs}</strong><span>{s.balls}</span><span>{s.fours}</span><span>{s.sixes}</span></div>)}</article><article className="dash-card" style={{marginTop:18}}><span className="card-kicker">BOWLING</span>{bowling.map(([pid,s])=><div key={pid} style={{display:'grid',gridTemplateColumns:'1fr repeat(3,80px)',padding:'11px 0',borderBottom:'1px solid #edf1ee'}}><span>{playerName(pid)}</span><strong>{Math.floor(s.balls/6)}.{s.balls%6}</strong><span>{s.runs}</span><span>{s.wickets}</span></div>)}</article></section></main>
}
