'use client'

import { useEffect, useState } from 'react'
import { useRouter } from 'next/navigation'
import { ArrowLeft, Search, Send, Trophy, UserRound } from 'lucide-react'
import { supabase } from '@/lib/supabase'

type Player={id:string;full_name:string|null;avatar_url:string|null;playing_role:string|null;batting_style:string|null;bowling_style:string|null}
export default function PlayersPage(){const router=useRouter();const [players,setPlayers]=useState<Player[]>([]);const [q,setQ]=useState('');const [loading,setLoading]=useState(true);const [sending,setSending]=useState('');const [message,setMessage]=useState('')
 useEffect(()=>{(async()=>{const {data:{user}}=await supabase.auth.getUser();if(!user){router.replace('/login');return};const {data}=await supabase.from('profiles').select('id,full_name,avatar_url,playing_role,batting_style,bowling_style').neq('id',user.id).order('full_name').limit(100);setPlayers(data||[]);setLoading(false)})()},[router])
 const filtered=players.filter(p=>(p.full_name||'').toLowerCase().includes(q.toLowerCase())||(p.playing_role||'').toLowerCase().includes(q.toLowerCase()))
 async function requestPlayer(playerId:string){setSending(playerId);setMessage('');const {data:{user}}=await supabase.auth.getUser();if(!user)return;const {error}=await supabase.from('player_requests').insert({from_player_id:user.id,to_player_id:playerId,status:'pending',request_type:'match'});setMessage(error?error.message:'Player request sent successfully.');setSending('')}
 if(loading)return <div className="loading-screen">Loading players…</div>
 return <main className="form-shell"><header className="topbar"><div className="brand"><Trophy size={22}/><span>Bosslive</span></div><button className="secondary-btn" onClick={()=>router.push('/dashboard')}><ArrowLeft size={16}/> Dashboard</button></header><section className="form-page"><span className="eyebrow">PLAYER DISCOVERY</span><h1>Find cricket players</h1><p>Search players by name or role and view their cricket profile.</p><div style={{position:'relative',marginTop:20}}><Search size={18} style={{position:'absolute',left:14,top:14,color:'#718078'}}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search player or role…" style={{width:'100%',padding:'13px 14px 13px 42px',border:'1px solid #dfe8e2',borderRadius:12}}/></div>{message&&<div className={message.includes('successfully')?'form-success':'form-error'} style={{marginTop:14}}>{message}</div>}<div style={{display:'grid',gap:12,marginTop:20}}>{filtered.map(p=><article className="dash-card" key={p.id} style={{display:'flex',alignItems:'center',gap:14}}><div className="avatar" style={{width:48,height:48,borderRadius:'50%',display:'grid',placeItems:'center',background:'#eaf8f1',color:'#078b56',fontWeight:800,overflow:'hidden'}}>{p.avatar_url?<img src={p.avatar_url} alt="" style={{width:'100%',height:'100%',objectFit:'cover'}}/>:<UserRound size={22}/>}</div><div style={{flex:1}}><h3>{p.full_name||'Player'}</h3><p>{p.playing_role||'Cricket player'}{p.batting_style?` · ${p.batting_style}`:''}</p></div><button className="secondary-btn" onClick={()=>router.push(`/players/${p.id}`)}>Profile</button><button className="primary-btn compact" disabled={sending===p.id} onClick={()=>requestPlayer(p.id)}><Send size={15}/> {sending===p.id?'Sending…':'Request'}</button></article>)}</div>{!filtered.length&&<div className="dash-card" style={{marginTop:20}}>No players found.</div>}</section></main>}
