'use client'

import { useEffect, useMemo, useState } from 'react'
import { useParams, useRouter } from 'next/navigation'
import { ArrowLeft, CircleDot, Trophy, Undo2 } from 'lucide-react'
import { supabase } from '@/lib/supabase'

type Match={id:string;team_a_id:string;team_b_id:string;overs:number;status:string;toss_winner_id?:string|null;toss_decision?:string|null;winner_team_id?:string|null;result_text?:string|null}
type Team={id:string;name:string}
type Player={player_id:string;full_name:string}
type Innings={id:string;batting_team_id:string;bowling_team_id:string;innings_number:number;status:string;total_runs:number;wickets:number;total_balls:number;extras:number}
type Delivery={id:string;over_number:number;ball_number:number;striker_id:string;bowler_id:string;runs_batter:number;runs_extras:number;extra_type:string|null;is_wicket:boolean;is_legal_ball:boolean;total_runs:number;commentary:string|null}

export default function LiveMatchPage(){
 const {id}=useParams<{id:string}>();const router=useRouter();const [match,setMatch]=useState<Match|null>(null);const [teams,setTeams]=useState<Team[]>([]);const [players,setPlayers]=useState<Player[]>([]);const [innings,setInnings]=useState<Innings|null>(null);const [deliveries,setDeliveries]=useState<Delivery[]>([]);const [striker,setStriker]=useState('');const [bowler,setBowler]=useState('');const [tossWinner,setTossWinner]=useState('');const [tossDecision,setTossDecision]=useState('bat');const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 async function load(){const {data:{user}}=await supabase.auth.getUser();if(!user){router.replace('/login');return};const {data:m}=await supabase.from('matches').select('id,team_a_id,team_b_id,overs,status,toss_winner_id,toss_decision,winner_team_id,result_text').eq('id',id).single();if(!m)return;setMatch(m);const {data:ts}=await supabase.from('teams').select('id,name').in('id',[m.team_a_id,m.team_b_id]);setTeams(ts||[]);let {data:ins}=await supabase.from('innings').select('id,batting_team_id,bowling_team_id,innings_number,status,total_runs,wickets,total_balls,extras').eq('match_id',id).order('innings_number').limit(1).maybeSingle();if(!ins&&!m.toss_winner_id)return;if(!ins&&m.toss_winner_id){const bat=m.toss_decision==='bat'?m.toss_winner_id:[m.team_a_id,m.team_b_id].find(x=>x!==m.toss_winner_id)!;const bowl=bat===m.team_a_id?m.team_b_id:m.team_a_id;const {data:created}=await supabase.from('innings').insert({match_id:id,batting_team_id:bat,bowling_team_id:bowl,innings_number:1,status:'live',total_runs:0,wickets:0,total_balls:0,extras:0}).select().single();ins=created}if(!ins)return;setInnings(ins);const {data:mp}=await supabase.from('match_players').select('player_id').eq('match_id',id).eq('team_id',ins.batting_team_id).eq('role','playing_xi');const pids=(mp||[]).map(x=>x.player_id);const {data:ps}=pids.length?await supabase.from('profiles').select('id,full_name').in('id',pids):{data:[] as any[]};setPlayers((ps||[]).map((p:any)=>({player_id:p.id,full_name:p.full_name})));const {data:ds}=await supabase.from('deliveries').select('id,over_number,ball_number,striker_id,bowler_id,runs_batter,runs_extras,extra_type,is_wicket,is_legal_ball,total_runs,commentary').eq('innings_id',ins.id).order('over_number').order('ball_number');setDeliveries(ds||[])}
 useEffect(()=>{load()},[id]);const score=useMemo(()=>deliveries.reduce((s,d)=>s+d.total_runs,0),[deliveries]);const wickets=useMemo(()=>deliveries.filter(d=>d.is_wicket).length,[deliveries]);const legalBalls=useMemo(()=>deliveries.filter(d=>d.is_legal_ball).length,[deliveries]);const overs=`${Math.floor(legalBalls/6)}.${legalBalls%6}`;const name=(tid:string)=>teams.find(t=>t.id===tid)?.name||'Team';
 async function saveToss(){if(!tossWinner)return;setBusy(true);const {error:e}=await supabase.from('matches').update({toss_winner_id:tossWinner,toss_decision:tossDecision,status:'live'}).eq('id',id);if(e)setError(e.message);else await load();setBusy(false)}
 async function addBall(runs:number,extraType:string|null=null,legal=true,wicket=false){if(!innings||!striker||!bowler){setError('Select striker and bowler first.');return};setBusy(true);setError('');const over=Math.floor(legalBalls/6);const ballNumber=legal?(legalBalls%6)+1:Math.min(20,deliveries.length+1);const {error:e}=await supabase.from('deliveries').insert({innings_id:innings.id,over_number:over,ball_number:ballNumber,striker_id:striker,bowler_id:bowler,runs_batter:extraType?0:runs,runs_extras:extraType?runs:0,extra_type:extraType,is_wicket:wicket,is_legal_ball:legal,commentary:wicket?'Wicket':extraType||`${runs} run${runs===1?'':'s'}`});if(e)setError(e.message);else await load();setBusy(false)}
 async function undo(){const last=deliveries[deliveries.length-1];if(!last)return;setBusy(true);const {error:e}=await supabase.from('deliveries').delete().eq('id',last.id);if(e)setError(e.message);else await load();setBusy(false)}
 async function finishInnings(){if(!innings)return;setBusy(true);await supabase.from('innings').update({status:'completed',total_runs:score,wickets,total_balls:legalBalls}).eq('id',innings.id);const {data:second}=await supabase.from('innings').select('id').eq('match_id',id).eq('innings_number',2).maybeSingle();if(!second){await supabase.rpc('ensure_second_innings',{p_match_id:id})}await load();setBusy(false)}
 async function finishMatch(){setBusy(true);const {error:e}=await supabase.rpc('calculate_match_result',{p_match_id:id});if(e)setError(e.message);else await load();setBusy(false)}
 if(!match)return <div className="loading-screen">Loading live match…</div>;
 if(!match.toss_winner_id)return <main className="form-shell"><header className="topbar"><div className="brand"><Trophy size={22}/><span>Bosslive</span></div><button className="secondary-btn" onClick={()=>router.push(`/matches/${id}`)}><ArrowLeft size={16}/> Match</button></header><section className="form-page"><span className="eyebrow">MATCH TOSS</span><h1>Who won the toss?</h1><div className="profile-form"><label>Winner<select value={tossWinner} onChange={e=>setTossWinner(e.target.value)}><option value="">Select team</option><option value={match.team_a_id}>{name(match.team_a_id)}</option><option value={match.team_b_id}>{name(match.team_b_id)}</option></select></label><label>Decision<select value={tossDecision} onChange={e=>setTossDecision(e.target.value)}><option value="bat">Bat first</option><option value="bowl">Bowl first</option></select></label>{error&&<div className="form-error">{error}</div>}<button className="primary-btn" disabled={busy} onClick={saveToss}>Save toss & start</button></div></section></main>;
 if(match.status==='completed')return <main className="form-shell"><section className="form-page"><span className="eyebrow">MATCH RESULT</span><h1>🏆 {match.result_text||'Match completed'}</h1><button className="primary-btn" onClick={()=>router.push(`/matches/${id}/scorecard`)}>View scorecard</button></section></main>;
 return <main className="form-shell"><header className="topbar"><div className="brand"><Trophy size={22}/><span>Bosslive</span></div><button className="secondary-btn" onClick={()=>router.push(`/matches/${id}`)}><ArrowLeft size={16}/> Match</button></header><section className="form-page"><span className="eyebrow"><CircleDot size={12}/> INNINGS {innings?.innings_number}</span><h1>{innings&&name(innings.batting_team_id)} batting</h1><div className="scoreboard"><strong>{score}/{wickets}</strong><span>{overs} overs</span></div>{innings&&<div className="profile-form"><h2>Ball control</h2><div className="form-grid"><label>Striker<select value={striker} onChange={e=>setStriker(e.target.value)}><option value="">Select batsman</option>{players.map(p=><option key={p.player_id} value={p.player_id}>{p.full_name}</option>)}</select></label><label>Bowler<select value={bowler} onChange={e=>setBowler(e.target.value)}><option value="">Select bowler</option>{players.map(p=><option key={p.player_id} value={p.player_id}>{p.full_name}</option>)}</select></label></div><div className="score-buttons">{[0,1,2,3,4,6].map(r=><button className="primary-btn compact" key={r} disabled={busy} onClick={()=>addBall(r)}>{r}</button>)}<button className="secondary-btn" disabled={busy} onClick={()=>addBall(1,'wide',false)}>WD</button><button className="secondary-btn" disabled={busy} onClick={()=>addBall(1,'no_ball',false)}>NB</button><button className="secondary-btn" disabled={busy} onClick={()=>addBall(0,null,true,true)}>W</button><button className="secondary-btn" disabled={busy} onClick={undo}><Undo2 size={16}/> Undo</button></div>{error&&<div className="form-error">{error}</div>}</div>}<div className="card-actions" style={{marginTop:18}}><button className="secondary-btn" disabled={busy} onClick={finishInnings}>Finish innings → Next innings</button>{innings?.innings_number===2&&<button className="primary-btn" disabled={busy} onClick={finishMatch}>Finish match & calculate winner 🏆</button>}</div><article className="dash-card" style={{marginTop:20}}><span className="card-kicker">BALL-BY-BALL</span>{deliveries.slice().reverse().slice(0,12).map(d=><div key={d.id} style={{display:'flex',justifyContent:'space-between',padding:'10px 0',borderBottom:'1px solid #edf1ee'}}><span>Over {d.over_number}.{d.ball_number}</span><strong>{d.is_wicket?'WICKET':d.extra_type?.toUpperCase()||d.runs_batter}</strong></div>)}</article></section></main>
}