'use client'

import { useEffect, useState } from 'react'
import { useParams, useRouter } from 'next/navigation'
import { ArrowLeft, Trophy } from 'lucide-react'
import { supabase } from '@/lib/supabase'

type Profile={id:string;full_name:string|null;avatar_url:string|null;playing_role:string|null;batting_style:string|null;bowling_style:string|null}
type Stats={matches:number;runs:number;wickets:number;highest_score:number;fours:number;sixes:number;fifties:number;hundreds:number;strike_rate:number;batting_average:number;economy:number}
export default function PublicPlayer(){const {id}=useParams<{id:string}>();const router=useRouter();const [p,setP]=useState<Profile|null>(null);const [s,setS]=useState<Stats|null>(null);useEffect(()=>{(async()=>{const {data}=await supabase.from('profiles').select('id,full_name,avatar_url,playing_role,batting_style,bowling_style').eq('id',id).single();setP(data);const {data:st}=await supabase.from('player_career_stats').select('*').eq('player_id',id).maybeSingle();setS(st as Stats|null)})()},[id]);if(!p)return <div className="loading-screen">Loading player…</div>;return <main className="form-shell"><header className="topbar"><div className="brand"><Trophy size={22}/><span>Bosslive</span></div><button className="secondary-btn" onClick={()=>router.push('/players')}><ArrowLeft size={16}/> Players</button></header><section className="form-page"><span className="eyebrow">PLAYER PROFILE</span><div style={{display:'flex',alignItems:'center',gap:18}}><div className="profile-avatar" style={{width:88,height:88,borderRadius:'50%',display:'grid',placeItems:'center',background:'#e7f8ef',color:'#078b56',fontSize:34,fontWeight:800,overflow:'hidden'}}>{p.avatar_url?<img src={p.avatar_url} alt="" style={{width:'100%',height:'100%',objectFit:'cover'}}/>:(p.full_name||'P').charAt(0)}</div><div><h1>{p.full_name||'Player'}</h1><p>{p.playing_role||'Cricket Player'} · {p.batting_style||'Batting style not set'}{p.bowling_style?` · ${p.bowling_style}`:''}</p></div></div><div className="stats-strip" style={{marginTop:24}}>{[['Matches',s?.matches||0],['Runs',s?.runs||0],['Wickets',s?.wickets||0],['SR',s?.strike_rate||0]].map(([a,b])=><div key={String(a)}><strong>{b}</strong><span>{a}</span></div>)}</div><div className="dashboard-grid" style={{marginTop:18}}>{[['Average',s?.batting_average||0],['Highest',s?.highest_score||0],['4s',s?.fours||0],['6s',s?.sixes||0],['50s',s?.fifties||0],['100s',s?.hundreds||0],['Economy',s?.economy||0]].map(([a,b])=><article className="dash-card" key={String(a)}><span className="card-kicker">{a}</span><h2>{b}</h2></article>)}</div></section></main>}
