'use client'

import { useEffect, useState } from 'react'
import { useParams, useRouter } from 'next/navigation'
import { ArrowLeft, Check, Users, Trophy } from 'lucide-react'
import { supabase } from '@/lib/supabase'

type Match={id:string;team_a_id:string;team_b_id:string;status:string};type Team={id:string;name:string};type P={id:string;full_name:string|null;avatar_url:string|null}
export default function PlayingXI(){const {id}=useParams<{id:string}>();const router=useRouter();const [match,setMatch]=useState<Match|null>(null);const [teams,setTeams]=useState<Team[]>([]);const [players,setPlayers]=useState<Record<string,P[]>>({});const [selected,setSelected]=useState<Record<string,string[]>>({});const [busy,setBusy]=useState(false);const [msg,setMsg]=useState('')
 useEffect(()=>{(async()=>{const {data:m}=await supabase.from('matches').select('id,team_a_id,team_b_id,status').eq('id',id).single();if(!m)return;setMatch(m);const {data:ts}=await supabase.from('teams').select('id,name').in('id',[m.team_a_id,m.team_b_id]);setTeams(ts||[]);for(const t of ts||[]){const {data:mem}=await supabase.from('team_members').select('player_id').eq('team_id',t.id);const pids=(mem||[]).map(x=>x.player_id);const {data:ps}=pids.length?await supabase.from('profiles').select('id,full_name,avatar_url').in('id',pids):{data:[] as any[]};setPlayers(x=>({...x,[t.id]:ps||[]}));const {data:existing}=await supabase.from('match_players').select('player_id').eq('match_id',id).eq('team_id',t.id).eq('role','playing_xi');setSelected(x=>({...x,[t.id]:(existing||[]).map(e=>e.player_id)}))}})()},[id])
 function toggle(tid:string,pid:string){setSelected(s=>{const a=s[tid]||[];if(a.includes(pid))return {...s,[tid]:a.filter(x=>x!==pid)};if(a.length>=11)return s;return {...s,[tid]:[...a,pid]}})}
 async function save(){if(!match)return;const a=selected[match.team_a_id]||[],b=selected[match.team_b_id]||[];if(a.length<11||b.length<11){setMsg('Select exactly 11 players for both teams.');return}setBusy(true);setMsg('');for(const t of teams){await supabase.from('match_players').delete().eq('match_id',id).eq('team_id',t.id).eq('role','playing_xi');const rows=(selected[t.id]||[]).map(pid=>({match_id:id,team_id:t.id,player_id:pid,role:'playing_xi'}));const {error}=await supabase.from('match_players').insert(rows);if(error){setMsg(error.message);setBusy(false);return}}await supabase.from('matches').update({status:'ready'}).eq('id',id);router.push(`/matches/${id}/live`);setBusy(false)}
 if(!match)return <div className="loading-screen">Loading playing XI…</div>;return <main className="form-shell"><header className="topbar"><div className="brand"><Trophy size={22}/><span>Bosslive</span></div><button className="secondary-btn" onClick={()=>router.push(`/matches/${id}`)}><ArrowLeft size={16}/> Match</button></header><section className="form-page"><span className="eyebrow"><Users size={13}/> PLAYING XI</span><h1>Select Playing XI</h1><p>Choose 11 players from each team. Selected players will be eligible for live scoring.</p>{teams.map(t=><article className="dash-card" style={{marginTop:18}} key={t.id}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><div><span className="card-kicker">TEAM</span><h2>{t.name}</h2></div><strong>{(selected[t.id]||[]).length}/11</strong></div><div style={{display:'grid',gap:8,marginTop:14}}>{(players[t.id]||[]).map(p=>{const on=(selected[t.id]||[]).includes(p.id);return <button key={p.id} onClick={()=>toggle(t.id,p.id)} style={{display:'flex',alignItems:'center',gap:12,padding:10,border:'1px solid '+(on?'#078b56':'#e1e8e3'),borderRadius:12,background:on?'#edf9f3':'white',textAlign:'left'}}><div style={{width:38,height:38,borderRadius:'50%',overflow:'hidden',display:'grid',placeItems:'center',background:'#eaf5ef'}}>{p.avatar_url?<img src={p.avatar_url} alt="" style={{width:'100%',height:'100%',objectFit:'cover'}}/>:<Users size={17}/>}</div><span style={{flex:1}}>{p.full_name||'Player'}</span>{on&&<Check size={18} color="#078b56"/>}</button>})}</div></article>)}{msg&&<div className="form-error" style={{marginTop:14}}>{msg}</div>}<button className="primary-btn" style={{marginTop:18}} disabled={busy} onClick={save}>{busy?'Saving…':'Save Playing XI → Toss'}</button></section></main>}
