'use client'

import { useEffect, useState } from 'react'
import { useRouter } from 'next/navigation'
import { ArrowLeft, CalendarPlus, Trophy } from 'lucide-react'
import { supabase } from '@/lib/supabase'

type Team={id:string;name:string}
export default function CreateMatch(){const router=useRouter();const [teams,setTeams]=useState<Team[]>([]);const [a,setA]=useState('');const [b,setB]=useState('');const [overs,setOvers]=useState(10);const [date,setDate]=useState('');const [busy,setBusy]=useState(false);const [msg,setMsg]=useState('')
 useEffect(()=>{(async()=>{const {data:{user}}=await supabase.auth.getUser();if(!user){router.replace('/login');return};const {data:m}=await supabase.from('team_members').select('team_id').eq('player_id',user.id);const ids=(m||[]).map(x=>x.team_id);if(ids.length){const {data:t}=await supabase.from('teams').select('id,name').in('id',ids);setTeams(t||[]);if(t?.[0])setA(t[0].id)}})()},[router])
 async function create(){if(!a||!b||a===b){setMsg('Select two different teams.');return}setBusy(true);setMsg('');const {data:{user}}=await supabase.auth.getUser();const {data:m,error}=await supabase.from('matches').insert({team_a_id:a,team_b_id:b,overs,status:'scheduled',match_date:date||new Date().toISOString(),created_by:user?.id}).select('id').single();if(error)setMsg(error.message);else router.push(`/matches/${m.id}`);setBusy(false)}
 return <main className="form-shell"><header className="topbar"><div className="brand"><Trophy size={22}/><span>Bosslive</span></div><button className="secondary-btn" onClick={()=>router.push('/dashboard')}><ArrowLeft size={16}/> Dashboard</button></header><section className="form-page"><span className="eyebrow"><CalendarPlus size={13}/> MATCH CENTER</span><h1>Create a match</h1><p>Choose existing teams, format and match time.</p><div className="profile-form"><label>My / Team A<select value={a} onChange={e=>setA(e.target.value)}><option value="">Select team</option>{teams.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><label>Opponent / Team B<select value={b} onChange={e=>setB(e.target.value)}><option value="">Select opponent</option>{teams.filter(t=>t.id!==a).map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><label>Overs<select value={overs} onChange={e=>setOvers(Number(e.target.value))}>{[5,10,15,20,50].map(x=><option key={x} value={x}>{x} overs</option>)}</select></label><label>Match date/time<input type="datetime-local" value={date} onChange={e=>setDate(e.target.value)}/></label>{msg&&<div className="form-error">{msg}</div>}<button className="primary-btn" disabled={busy} onClick={create}>{busy?'Creating…':'Create Match →'}</button></div></section></main>}
