'use client'

import { useEffect, useState } from 'react'
import { useParams, useRouter } from 'next/navigation'
import { ArrowLeft, Check, Send, Trophy, UserPlus, X } from 'lucide-react'
import { supabase } from '@/lib/supabase'

type Match={id:string;team_a_id:string;team_b_id:string};type Team={id:string;name:string};type Player={id:string;full_name:string|null;avatar_url:string|null};type Req={id:string;player_id:string;status:string;full_name:string|null;avatar_url:string|null}
export default function MatchRequests(){const {id}=useParams<{id:string}>();const router=useRouter();const [match,setMatch]=useState<Match|null>(null);const [teams,setTeams]=useState<Team[]>([]);const [members,setMembers]=useState<Player[]>([]);const [requests,setRequests]=useState<Req[]>([]);const [selected,setSelected]=useState('');const [busy,setBusy]=useState(false);const [msg,setMsg]=useState('')
 async function load(){const {data:m}=await supabase.from('matches').select('id,team_a_id,team_b_id').eq('id',id).single();if(!m)return;setMatch(m);const {data:ts}=await supabase.from('teams').select('id,name').in('id',[m.team_a_id,m.team_b_id]);setTeams(ts||[]);const teamIds=(ts||[]).map(t=>t.id);const {data:tm}=teamIds.length?await supabase.from('team_members').select('team_id,player_id').in('team_id',teamIds):{data:[] as any[]};const pids=(tm||[]).map(x=>x.player_id);const {data:ps}=pids.length?await supabase.from('profiles').select('id,full_name,avatar_url').in('id',pids):{data:[] as any[]};setMembers((ps||[]).filter((p:any)=>p.id));const {data:r}=await supabase.from('match_player_requests').select('id,player_id,status').eq('match_id',id).order('created_at',{ascending:false});const rids=(r||[]).map(x=>x.player_id);const {data:rps}=rids.length?await supabase.from('profiles').select('id,full_name,avatar_url').in('id',rids):{data:[] as any[]};setRequests((r||[]).map(x=>({...x,full_name:(rps||[]).find((p:any)=>p.id===x.player_id)?.full_name||'Player',avatar_url:(rps||[]).find((p:any)=>p.id===x.player_id)?.avatar_url||null}))) }
 useEffect(()=>{load()},[id]);
 async function send(){if(!selected)return;setBusy(true);const {data:{user}}=await supabase.auth.getUser();const {error}=await supabase.from('match_player_requests').insert({match_id:id,player_id:selected,requested_by:user?.id,status:'pending'});setMsg(error?.message||'Match request sent.');setSelected('');await load();setBusy(false)}
 async function decide(rid:string,accept:boolean){setBusy(true);const {error}=await supabase.from('match_player_requests').update({status:accept?'accepted':'rejected',responded_at:new Date().toISOString()}).eq('id',rid);if(!error&&accept){const r=requests.find(x=>x.id===rid);if(r&&match){const {data:{user}}=await supabase.auth.getUser();const {data:mp}=await supabase.from('team_members').select('team_id').eq('player_id',r.player_id).in('team_id',[match.team_a_id,match.team_b_id]).maybeSingle();if(mp)await supabase.from('match_players').upsert({match_id:id,team_id:mp.team_id,player_id:r.player_id,role:'playing_xi'},{onConflict:'match_id,player_id'})}}setMsg(error?.message||(accept?'Player accepted for match.':'Request rejected.'));await load();setBusy(false)}
 return <main className="form-shell"><header className="topbar"><div className="brand"><Trophy size={22}/><span>Bosslive</span></div><button className="secondary-btn" onClick={()=>router.push(`/matches/${id}`)}><ArrowLeft size={16}/> Match</button></header><section className="form-page"><span className="eyebrow"><UserPlus size={13}/> MATCH REQUESTS</span><h1>Players for this match</h1><p>Invite players from the participating teams and manage their responses.</p><article className="dash-card" style={{marginTop:18}}><span className="card-kicker"><Send size={13}/> SEND REQUEST</span><div style={{display:'flex',gap:10,marginTop:12}}><select value={selected} onChange={e=>setSelected(e.target.value)} style={{flex:1}}><option value="">Select player</option>{members.map(p=><option key={p.id} value={p.id}>{p.full_name||'Player'}</option>)}</select><button className="primary-btn" disabled={busy||!selected} onClick={send}>Invite</button></div></article><article className="dash-card" style={{marginTop:18}}><span className="card-kicker">REQUESTS</span>{requests.length?requests.map(r=><div key={r.id} style={{display:'flex',alignItems:'center',gap:12,padding:'12px 0',borderBottom:'1px solid #edf1ee'}}><div style={{width:42,height:42,borderRadius:'50%',overflow:'hidden',background:'#eaf5ef',display:'grid',placeItems:'center'}}>{r.avatar_url?<img src={r.avatar_url} alt="" style={{width:'100%',height:'100%',objectFit:'cover'}}/>:<UserPlus size={18}/>}</div><div style={{flex:1}}><strong>{r.full_name}</strong><small style={{display:'block',color:'#718078'}}>{r.status}</small></div>{r.status==='pending'&&<><button className="primary-btn compact" disabled={busy} onClick={()=>decide(r.id,true)}><Check size={15}/> Accept</button><button className="secondary-btn" disabled={busy} onClick={()=>decide(r.id,false)}><X size={15}/> Reject</button></>}</div>):<p>No match requests yet.</p>}</article>{msg&&<div className="form-success" style={{marginTop:14}}>{msg}</div>}<button className="primary-btn" style={{marginTop:18}} onClick={()=>router.push(`/matches/${id}/playing-xi`)}>Continue to Playing XI →</button></section></main>}
