'use client'

import { useEffect, useState } from 'react'
import { useRouter } from 'next/navigation'
import { ArrowLeft, Trophy } from 'lucide-react'
import { supabase } from '@/lib/supabase'

type Stats={matches:number;innings:number;runs:number;balls_faced:number;strike_rate:number;batting_average:number;highest_score:number;fifties:number;hundreds:number;fours:number;sixes:number;wickets:number;economy:number}
export default function StatsPage(){const router=useRouter();const [stats,setStats]=useState<Stats|null>(null);const [name,setName]=useState('Player');useEffect(()=>{(async()=>{const {data:{user}}=await supabase.auth.getUser();if(!user){router.replace('/login');return};const {data:p}=await supabase.from('profiles').select('full_name').eq('id',user.id).maybeSingle();setName(p?.full_name||'Player');const {data:s}=await supabase.from('player_profile_stats').select('*').eq('player_id',user.id).maybeSingle();setStats(s as Stats|null)})()},[router]);return <main className="form-shell"><header className="topbar"><div className="brand"><Trophy size={22}/><span>Bosslive</span></div><button className="secondary-btn" onClick={()=>router.push('/dashboard')}><ArrowLeft size={16}/> Dashboard</button></header><section className="form-page"><span className="eyebrow">CAREER PROFILE</span><h1>{name}</h1><p>Your performance record updates from recorded match data.</p><div className="stats-strip" style={{marginTop:24}}><div><strong>{stats?.matches||0}</strong><span>Matches</span></div><div><strong>{stats?.runs||0}</strong><span>Runs</span></div><div><strong>{stats?.wickets||0}</strong><span>Wickets</span></div><div><strong>{stats?.strike_rate||0}</strong><span>Strike Rate</span></div></div><div className="dashboard-grid" style={{marginTop:18}}>{[['Average',stats?.batting_average||0],['Highest',stats?.highest_score||0],['4s',stats?.fours||0],['6s',stats?.sixes||0],['50s',stats?.fifties||0],['100s',stats?.hundreds||0],['Economy',stats?.economy||0],['Innings',stats?.innings||0]].map(([label,value])=><article className="dash-card" key={String(label)}><span className="card-kicker">{label}</span><h2>{value}</h2></article>)}</div></section></main>}
